bdd_profil_answer_question_script
WildCodeSchool/lyon-php-2003-project2-setmind pull request #168
Opened 2020-05-11 17:05 UTC by zazalit

2020-05-11 17:07 UTC, Ben2669 approved these changes
Ok pour moi !

2020-05-11 20:16 UTC, Ben2669 requested changes
Il faut remplacer les apostrophes qui cassent les strings (comme j'ai fait hier) car une partie des requêtes passe en commentaires

2020-05-12 00:26 UTC, actix2013 approved these changes

2020-05-12 14:45 UTC, Ben2669 approved these changes
Ok cool !

2020-05-12 14:45 UTC, merged